name: Node.js CI on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull new commits
        run: git pull origin main
        working-directory: e:\www\express

      - name: Install dependencies
        run: npm install
        working-directory: e:\www\express
